#!/bin/bash
#
# 01-setup.sh - Raspberry Pi Print Server Initial Setup
#
# Installs and configures CUPS, Avahi, and printer drivers for:
#   - Dymo LabelWriter 4XL
#   - Dymo LabelWriter 450 Turbo
#   - HP LaserJet 1320
#
# Run as root or with sudo on Raspberry Pi OS Lite (Bookworm)
#

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# --- Preflight checks ---

if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root. Use: sudo $0"
    exit 1
fi

CURRENT_USER="${SUDO_USER:-$(whoami)}"
log_info "Running setup for user: $CURRENT_USER"

# --- Check architecture ---

ARCH=$(dpkg --print-architecture)
log_info "Detected architecture: $ARCH"
if [[ "$ARCH" != "armhf" && "$ARCH" != "arm64" ]]; then
    log_warn "Expected ARM architecture (armhf or arm64), got: $ARCH"
    log_warn "This script is designed for Raspberry Pi. Continuing anyway..."
fi

# --- Check available memory and configure swap if needed ---

TOTAL_MEM_KB=$(grep MemTotal /proc/meminfo | awk '{print $2}')
TOTAL_MEM_MB=$((TOTAL_MEM_KB / 1024))
log_info "Total RAM: ${TOTAL_MEM_MB}MB"

SWAP_TOTAL_KB=$(grep SwapTotal /proc/meminfo | awk '{print $2}')
SWAP_TOTAL_MB=$((SWAP_TOTAL_KB / 1024))
log_info "Current swap: ${SWAP_TOTAL_MB}MB"

if [[ $SWAP_TOTAL_MB -lt 100 ]]; then
    log_warn "Swap is low (${SWAP_TOTAL_MB}MB). Configuring 512MB swap..."
    if [[ -f /etc/dphys-swapfile ]]; then
        sed -i 's/^CONF_SWAPSIZE=.*/CONF_SWAPSIZE=512/' /etc/dphys-swapfile
        systemctl restart dphys-swapfile
        log_info "Swap configured to 512MB via dphys-swapfile"
    else
        log_warn "dphys-swapfile not found. Consider setting up swap manually."
    fi
fi

# --- Update system ---

log_info "Updating package lists..."
apt-get update

log_info "Upgrading installed packages..."
apt-get upgrade -y

# --- Install required packages ---

log_info "Installing CUPS and printing system..."
apt-get install -y \
    cups \
    cups-client \
    cups-bsd \
    cups-filters

log_info "Installing Avahi (mDNS/Bonjour) for network discovery..."
apt-get install -y \
    avahi-daemon \
    avahi-utils

log_info "Installing HP printer drivers (hplip)..."
apt-get install -y \
    hplip \
    hplip-data

log_info "Installing Dymo printer drivers..."
apt-get install -y \
    printer-driver-dymo

log_info "Installing additional utilities..."
apt-get install -y \
    usbutils \
    lsb-release

# --- Configure CUPS ---

log_info "Configuring CUPS..."

# Backup original config
CUPSD_CONF="/etc/cups/cupsd.conf"
if [[ ! -f "${CUPSD_CONF}.bak" ]]; then
    cp "$CUPSD_CONF" "${CUPSD_CONF}.bak"
    log_info "Backed up original cupsd.conf to ${CUPSD_CONF}.bak"
fi

# Configure CUPS to listen on all interfaces
cat > "$CUPSD_CONF" << 'CUPSCONF'
# CUPS configuration for Raspberry Pi Print Server
# Generated by print-server setup script

LogLevel warn
MaxLogSize 0
PageLogFormat

# Listen on all interfaces, port 631
Port 631
Listen /run/cups/cups.sock

# Enable printer browsing and sharing
Browsing On
BrowseLocalProtocols dnssd

# Default authentication type
DefaultAuthType Basic

# Web interface enabled
WebInterface Yes

# Share printers by default
DefaultShared Yes

# Server access - allow local network
<Location />
  Order allow,deny
  Allow @LOCAL
</Location>

# Admin pages - allow local network
<Location /admin>
  Order allow,deny
  Allow @LOCAL
</Location>

# Admin config changes - allow local network
<Location /admin/conf>
  AuthType Default
  Require user @SYSTEM
  Order allow,deny
  Allow @LOCAL
</Location>

# Printer operations - allow local network
<Policy default>
  JobPrivateAccess default
  JobPrivateValues default
  SubscriptionPrivateAccess default
  SubscriptionPrivateValues default

  <Limit Create-Job Print-Job Print-URI Validate-Job>
    Order deny,allow
  </Limit>

  <Limit Send-Document Send-URI Hold-Job Release-Job Restart-Job Purge-Jobs Set-Job-Attributes Create-Job-Subscription Renew-Subscription Cancel-Subscription Get-Notifications Reprocess-Job Cancel-Current-Job Suspend-Current-Job Resume-Job Cancel-My-Jobs Close-Job CUPS-Move-Job CUPS-Get-Document>
    Require user @OWNER @SYSTEM
    Order deny,allow
  </Limit>

  <Limit CUPS-Add-Modify-Printer CUPS-Delete-Printer CUPS-Add-Modify-Class CUPS-Delete-Class CUPS-Set-Default CUPS-Get-Devices>
    AuthType Default
    Require user @SYSTEM
    Order deny,allow
  </Limit>

  <Limit Pause-Printer Resume-Printer Enable-Printer Disable-Printer Pause-Printer-After-Current-Job Hold-New-Jobs Release-Held-New-Jobs Deactivate-Printer Activate-Printer Restart-Printer Shutdown-Printer Startup-Printer Promote-Job Schedule-Job-After Cancel-Jobs CUPS-Accept-Jobs CUPS-Reject-Jobs>
    AuthType Default
    Require user @SYSTEM
    Order deny,allow
  </Limit>

  <Limit Cancel-Job CUPS-Authenticate-Job>
    Require user @OWNER @SYSTEM
    Order deny,allow
  </Limit>

  <Limit All>
    Order deny,allow
  </Limit>
</Policy>
CUPSCONF

log_info "CUPS configured to listen on all interfaces"

# --- Add user to lpadmin group ---

log_info "Adding user '$CURRENT_USER' to lpadmin group..."
usermod -aG lpadmin "$CURRENT_USER"

# --- Configure Avahi ---

log_info "Configuring Avahi..."

AVAHI_CONF="/etc/avahi/avahi-daemon.conf"
if [[ ! -f "${AVAHI_CONF}.bak" ]]; then
    cp "$AVAHI_CONF" "${AVAHI_CONF}.bak"
    log_info "Backed up original avahi-daemon.conf"
fi

# Ensure Avahi is configured to publish services
sed -i 's/^#\?publish-hinfo=.*/publish-hinfo=yes/' "$AVAHI_CONF"
sed -i 's/^#\?publish-workstation=.*/publish-workstation=yes/' "$AVAHI_CONF"

# --- Configure firewall (if ufw is active) ---

if command -v ufw &>/dev/null; then
    UFW_STATUS=$(ufw status | head -1)
    if [[ "$UFW_STATUS" == *"active"* ]]; then
        log_info "Configuring firewall rules..."
        ufw allow 631/tcp comment "CUPS web interface and IPP"
        ufw allow 5353/udp comment "mDNS/Avahi discovery"
        log_info "Firewall rules added for CUPS (631/tcp) and mDNS (5353/udp)"
    else
        log_info "UFW is installed but not active. No firewall rules needed."
    fi
else
    log_info "UFW not installed. No firewall configuration needed."
fi

# --- Enable and start services ---

log_info "Enabling and starting CUPS..."
systemctl enable cups
systemctl restart cups

log_info "Enabling and starting Avahi..."
systemctl enable avahi-daemon
systemctl restart avahi-daemon

# --- Verify installation ---

log_info "Verifying installation..."

echo ""
echo "========================================="
echo " Installation Summary"
echo "========================================="
echo ""

# Check CUPS
if systemctl is-active --quiet cups; then
    log_info "CUPS service: RUNNING"
else
    log_error "CUPS service: NOT RUNNING"
fi

# Check Avahi
if systemctl is-active --quiet avahi-daemon; then
    log_info "Avahi service: RUNNING"
else
    log_error "Avahi service: NOT RUNNING"
fi

# Check installed drivers
echo ""
log_info "Installed printer drivers:"
dpkg -l | grep -E "(printer-driver-dymo|hplip)" | awk '{print "  " $2 " - " $3}'

# Show detected USB devices
echo ""
log_info "Connected USB devices:"
lsusb | grep -iE "(dymo|hewlett|hp|printer)" || log_warn "No printer USB devices detected (connect printers and re-check)"

# Show IP address
echo ""
PI_IP=$(hostname -I | awk '{print $1}')
log_info "Raspberry Pi IP address: $PI_IP"
log_info "CUPS web interface: https://$PI_IP:631"

echo ""
echo "========================================="
echo " Setup complete!"
echo "========================================="
echo ""
echo "Next steps:"
echo "  1. Connect your USB printers to the Raspberry Pi"
echo "  2. Run: sudo ./02-configure-printers.sh"
echo "  3. Access CUPS web interface at: https://$PI_IP:631"
echo "     Username: $CURRENT_USER"
echo "     Password: (your Linux password)"
echo ""
