#!/bin/bash
#
# 03-airprint.sh - Configure AirPrint via Avahi
#
# Creates Avahi service files so iOS/macOS devices can discover
# the shared CUPS printers automatically via AirPrint (Bonjour/mDNS).
#
# CUPS on Bookworm with Avahi generally handles AirPrint advertisement
# automatically, but this script ensures proper service files exist
# and verifies everything is working.
#
# Run as root or with sudo after 02-configure-printers.sh
#

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

log_info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }
log_step()  { echo -e "${CYAN}[STEP]${NC} $1"; }

if [[ $EUID -ne 0 ]]; then
    log_error "This script must be run as root. Use: sudo $0"
    exit 1
fi

# --- Verify services are running ---

if ! systemctl is-active --quiet cups; then
    log_error "CUPS is not running. Run 01-setup.sh first."
    exit 1
fi

if ! systemctl is-active --quiet avahi-daemon; then
    log_error "Avahi is not running. Run 01-setup.sh first."
    exit 1
fi

AVAHI_SERVICES_DIR="/etc/avahi/services"
PI_HOSTNAME=$(hostname)
PI_IP=$(hostname -I | awk '{print $1}')

# --- Ensure CUPS is configured to share via dnssd ---

log_step "Verifying CUPS sharing configuration..."

# Check that BrowseLocalProtocols includes dnssd
if grep -q "BrowseLocalProtocols dnssd" /etc/cups/cupsd.conf; then
    log_info "CUPS is configured to browse via dnssd"
else
    log_warn "Adding dnssd browsing to CUPS configuration..."
    if grep -q "^BrowseLocalProtocols" /etc/cups/cupsd.conf; then
        sed -i 's/^BrowseLocalProtocols.*/BrowseLocalProtocols dnssd/' /etc/cups/cupsd.conf
    else
        echo "BrowseLocalProtocols dnssd" >> /etc/cups/cupsd.conf
    fi
    systemctl restart cups
    log_info "CUPS restarted with dnssd browsing enabled"
fi

# --- Ensure all printers are shared ---

log_step "Ensuring all printers are shared..."

for PRINTER in $(lpstat -p 2>/dev/null | awk '{print $2}'); do
    SHARED=$(lpoptions -p "$PRINTER" -l 2>/dev/null | grep -c "printer-is-shared" || true)
    lpadmin -p "$PRINTER" -o printer-is-shared=true
    log_info "Printer '$PRINTER' is shared"
done

# --- Create Avahi service files for each printer ---
#
# While CUPS+Avahi usually auto-advertise shared printers, explicit
# service files give us more control over the advertised metadata
# (which improves compatibility with iOS/macOS AirPrint).

log_step "Creating Avahi service files for AirPrint..."

# Function to generate an Avahi service file for a printer
create_airprint_service() {
    local printer_name="$1"
    local printer_desc="$2"
    local printer_type="$3"  # e.g., "application/pdf" or "image/pwg-raster"
    local rp_value="$4"      # Resource path: printers/<name>

    local service_file="${AVAHI_SERVICES_DIR}/AirPrint-${printer_name}.service"

    cat > "$service_file" << EOF
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE service-group SYSTEM "avahi-service.dtd">

<!--
  AirPrint service file for $printer_desc
  Generated by print-server setup script
-->

<service-group>
  <name replace-wildcards="yes">AirPrint ${printer_desc} @ %h</name>

  <service>
    <type>_ipp._tcp</type>
    <subtype>_universal._sub._ipp._tcp</subtype>
    <port>631</port>
    <txt-record>txtvers=1</txt-record>
    <txt-record>qtotal=1</txt-record>
    <txt-record>rp=${rp_value}</txt-record>
    <txt-record>ty=${printer_desc}</txt-record>
    <txt-record>adminurl=https://${PI_HOSTNAME}.local:631/printers/${printer_name}</txt-record>
    <txt-record>note=${printer_desc}</txt-record>
    <txt-record>priority=0</txt-record>
    <txt-record>product=(${printer_desc})</txt-record>
    <txt-record>pdl=${printer_type}</txt-record>
    <txt-record>URF=DM3</txt-record>
    <txt-record>TLS=1.2</txt-record>
    <txt-record>printer-state=3</txt-record>
    <txt-record>printer-type=0x801046</txt-record>
  </service>
</service-group>
EOF

    log_info "Created AirPrint service file: $service_file"
}

# HP LaserJet 1320 - supports PostScript and PDF
create_airprint_service \
    "HP-LaserJet-1320" \
    "HP LaserJet 1320" \
    "application/octet-stream,application/pdf,application/postscript,image/jpeg,image/png,image/pwg-raster,image/urf" \
    "printers/HP-LaserJet-1320"

# Dymo LabelWriter 4XL - label printer
create_airprint_service \
    "Dymo-LabelWriter-4XL" \
    "Dymo LabelWriter 4XL" \
    "application/octet-stream,application/pdf,image/jpeg,image/png,image/pwg-raster,image/urf" \
    "printers/Dymo-LabelWriter-4XL"

# Dymo LabelWriter 450 Turbo - label printer
create_airprint_service \
    "Dymo-LabelWriter-450-Turbo" \
    "Dymo LabelWriter 450 Turbo" \
    "application/octet-stream,application/pdf,image/jpeg,image/png,image/pwg-raster,image/urf" \
    "printers/Dymo-LabelWriter-450-Turbo"

# --- Restart Avahi to pick up new service files ---

log_step "Restarting Avahi daemon..."
systemctl restart avahi-daemon
sleep 2

# --- Verify AirPrint services are advertised ---

log_step "Verifying AirPrint advertisement..."
echo ""

# Check that Avahi is publishing the services
SERVICES_FOUND=$(avahi-browse -t _ipp._tcp 2>/dev/null || true)

if [[ -n "$SERVICES_FOUND" ]]; then
    log_info "AirPrint services detected on the network:"
    echo "$SERVICES_FOUND" | grep -i "airprint\|HP\|Dymo\|LabelWriter\|LaserJet" || echo "$SERVICES_FOUND"
else
    log_warn "No AirPrint services detected yet. This may take a moment."
    log_warn "Try running: avahi-browse -t _ipp._tcp"
fi

echo ""

# --- Also verify with avahi-browse for _universal._sub._ipp._tcp ---

log_step "Checking universal subtype advertisement..."
UNIVERSAL_FOUND=$(avahi-browse -t _universal._sub._ipp._tcp 2>/dev/null || true)

if [[ -n "$UNIVERSAL_FOUND" ]]; then
    log_info "Universal IPP subtype services (required for AirPrint):"
    echo "$UNIVERSAL_FOUND"
else
    log_warn "Universal subtype not yet visible. Give Avahi a few seconds."
fi

# --- List service files ---

echo ""
log_step "Installed Avahi service files:"
ls -la "$AVAHI_SERVICES_DIR"/AirPrint-*.service 2>/dev/null || log_warn "No AirPrint service files found"

# =========================================
# Summary
# =========================================

echo ""
echo "========================================="
echo " AirPrint Configuration Summary"
echo "========================================="
echo ""
log_info "AirPrint is now configured for all shared printers."
echo ""
echo "Service files created in: $AVAHI_SERVICES_DIR/"
echo ""
echo "How clients discover printers:"
echo "  iOS/macOS:  Automatic via AirPrint (Settings > Print)"
echo "  Windows 10+: Settings > Printers > Add printer (via IPP)"
echo "               Or use: ipp://$PI_IP:631/printers/<PrinterName>"
echo "  Linux:      auto-discovered via Avahi, or add manually in CUPS"
echo ""
echo "Printer URLs:"
echo "  HP LaserJet 1320:         ipp://$PI_HOSTNAME.local:631/printers/HP-LaserJet-1320"
echo "  Dymo LabelWriter 4XL:    ipp://$PI_HOSTNAME.local:631/printers/Dymo-LabelWriter-4XL"
echo "  Dymo LabelWriter 450:    ipp://$PI_HOSTNAME.local:631/printers/Dymo-LabelWriter-450-Turbo"
echo ""
echo "Troubleshooting:"
echo "  - Browse services:  avahi-browse -a"
echo "  - Check IPP:        avahi-browse -t _ipp._tcp"
echo "  - Resolve printer:  avahi-resolve -n $PI_HOSTNAME.local"
echo "  - CUPS web UI:      https://$PI_IP:631"
echo ""
